### ISSUE TITLE
Releases are not published on maven public repository

### ISSUE THREAD

**Issue by vanblue** [amedia/meteo#6]
Hi. Thanks for developing this nice library.

Can you publish new releases (I am thinking about 3.0.11 and others) to public maven repository? I found only 3.0.1 (https://mvnrepository.com/artifact/no.api.meteo/meteo-core). Furthermore I cannot install you library in my maven repository from source, because I cannot find parent pom project (no.api.maven:amedia-maven:0.1.6).

**Comment by vanblue** [comment]
@lazee could you do something with this issue? :)

**Comment by lazee** [comment]
@vanblue Sorry for never answering this issue! Somehow I totally missed it  We are working on fixing all these issues, but I guess thats a little bit too late for you(?).
